{"test_num": 4, "errors": [], "failures": [{"module": "FirsTest", "error_type": "test_case", "case_name": "test_assert_failed", "exception": "Traceback (most recent call last):\n  File \"G:\\\u5fae\u4fe1\u5c0f\u7a0b\u5e8f\\minium-0.0.2\\minium-0.0.2\\first_test.py\", line 20, in test_assert_failed\n    self.assertEqual(self.page.path, \"/pages/home/user/index\")\n  File \"D:\\Program Files\\Python37\\lib\\site-packages\\minium-0.0.2-py3.7.egg\\minium\\framework\\assertbase.py\", line 170, in _hook_assert\n    attr(*args,**kwargs)\nAssertionError: '/pages/home/selfservice/index' != '/pages/home/user/index'\n- /pages/home/selfservice/index\n?             ^^^^   ----\n+ /pages/home/user/index\n?             ^\n\n"}], "class_errors": [], "class_failures": []}